#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path';
import {walk,parseFrontmatter,ciPaths,readJson,writeJsonAtomic,slug,sha256,dateOnly} from './ci-lib.mjs';
const vault=path.resolve(process.argv[2]||process.cwd()); const p=ciPaths(vault); const reg=readJson(p.candidates,{registry_id:'omar-brain-learning-candidates-v1',version:'1.0',candidates:[]}); const existing=new Map((reg.candidates||[]).map(c=>[c.candidate_key,c]));
function section(body,title){const re=new RegExp(`^##\\s+${title}\\s*$([\\s\\S]*?)(?=^##\\s+|\\Z)`,'gmi');const m=re.exec(body);return m?m[1]:''}
function bullets(s){return s.split(/\r?\n/).map(x=>x.match(/^\s*[-*]\s+(.+)/)?.[1]?.trim()).filter(Boolean).filter(x=>!/^none\b|^no reusable learning\b/i.test(x))}
const runs=walk(path.join(vault,'40_Projects')).filter(f=>f.endsWith('.md')).map(f=>({f,...parseFrontmatter(fs.readFileSync(f,'utf8'))})).filter(x=>x.data.type==='run'&&['observed','verified','runtime-verified','repo-verified'].includes(x.data.verification_state)); let discovered=0;
for(const r of runs){const runId=r.data.run_id||path.basename(r.f,'.md'), projectId=r.data.project_id||''; const lessonClaims=[...bullets(section(r.body,'Reusable learning candidates')),...bullets(section(r.body,'Learning candidates'))];const groups=[['lesson',[...new Set(lessonClaims)]],['failure-signature',bullets(section(r.body,'Failure signatures'))]];
  for(const [kind,claims] of groups)for(const claim of claims){const key=sha256(`${kind}:${claim.toLowerCase().replace(/\s+/g,' ').trim()}`);const cur=existing.get(key);if(cur){cur.source_runs=[...new Set([...(cur.source_runs||[]),runId])];cur.projects=[...new Set([...(cur.projects||[]),projectId].filter(Boolean))];cur.validation_count=cur.source_runs.length;cur.updated=dateOnly();}else{const c={candidate_id:`lc-${slug(claim).slice(0,40)}-${key.slice(0,8)}`,candidate_key:key,kind,claim,status:'proposed',source_runs:[runId],projects:[projectId].filter(Boolean),validation_count:1,independent_project_count:projectId?1:0,authority:'run-derived-candidate',created:dateOnly(),updated:dateOnly(),promotion_rule:'Never auto-promote; require evidence and governance review.'};existing.set(key,c);discovered++;}}
}
reg.candidates=[...existing.values()].map(c=>({...c,independent_project_count:new Set(c.projects||[]).size}));reg.updated=dateOnly();writeJsonAtomic(p.candidates,reg);console.log(JSON.stringify({runs_scanned:runs.length,new_candidates:discovered,total_candidates:reg.candidates.length},null,2));
