#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path';
import {resolveProject,id,slug,dateOnly,now,loadRegistry,saveRegistry,appendProvenance,appendEvent,enqueueImpact,appendJsonl,ciPaths} from './ci-lib.mjs';
const args=process.argv.slice(2);const vault=path.resolve(args[0]||process.cwd());const get=(n,f='')=>{const i=args.indexOf(`--${n}`);return i>=0?args[i+1]:f};
const projectHint=get('project'),title=get('title'),result=get('result','partial'),summary=get('summary','');
if(!projectHint||!title){console.error('Usage: node new-run.mjs <vault> --project "Meta Word of Mouth" --title "Webhook verification" --result success|failed|partial [--summary "..."]');process.exit(2)}
if(!['success','failed','partial','blocked'].includes(result)){console.error(`Invalid result ${result}`);process.exit(2)}
const r=resolveProject(vault,projectHint);if(r.status!=='resolved'){console.error(JSON.stringify(r,null,2));process.exit(1)}
const runId=id('run'),dirRel=r.project.learning?.runs;if(!dirRel){console.error('Resolved project manifest has no learning.runs destination');process.exit(1)}const dir=path.join(vault,...dirRel.split('/'));fs.mkdirSync(dir,{recursive:true});const rel=path.posix.join(dirRel,`${dateOnly()}-${slug(title)}-${runId.slice(-8)}.md`),abs=path.join(vault,...rel.split('/'));
const status=result==='failed'?'failed':result==='blocked'?'blocked':'completed';const note=`---\ntype: run\nstatus: ${status}\ncreated: ${dateOnly()}\nupdated: ${dateOnly()}\ntopics: [execution-run, real-project-experience]\nai_access: allowed\nproject_id: ${r.project.project_id}\nrun_id: ${runId}\nresult: ${result}\nverification_state: observed\nsource_kind: runtime\nconfidence: medium\n---\n# ${title}\n\n## Objective\n${summary||'Record the real execution outcome.'}\n\n## Starting state\n\n## Resolved project/revision\n- Project: ${r.project.project_id}\n- Repository/revision: verify and record\n\n## Work executed\n\n## Files/artifacts changed\n\n## Verification run\n\`\`\`text\n\n\`\`\`\n\n## Results\n- Result: ${result}\n\n## Failures encountered\n\n## Root causes\n\n## Repairs\n\n## Remaining work\n\n## Exact next action\n\n## Learning review\n- performed: true\n- outcome: NO_REUSABLE_LEARNING\n\n## Reusable learning candidates\n\n## Failure signatures\n\n## Evidence links\n\n## Cross-project implications\n- none identified\n`;
fs.writeFileSync(abs,note,'utf8');const registry=loadRegistry(vault);const objectId=`obj-${runId}`;registry.objects.push({object_id:objectId,object_type:'run',title,canonical_path:rel,status,authority:'observed',verification_state:'observed',project_id:r.project.project_id,summary:summary||`${result} run: ${title}`,created_at:now(),updated_at:now()});saveRegistry(vault,registry);const prov=appendProvenance(vault,{object_id:objectId,source_type:'runtime-run-record',source_ref:rel,authority:'observed',verification_state:'observed'});const projectObject=(registry.objects||[]).find(o=>o.object_type==='project'&&o.project_id===r.project.project_id);if(projectObject)appendJsonl(ciPaths(vault).edges,{edge_id:id('edge'),from:objectId,relation:'belongs_to',to:projectObject.object_id,project_id:r.project.project_id,created_at:now()});const evt=appendEvent(vault,{event_type:status==='failed'?'run.failed':'run.completed',project_id:r.project.project_id,run_id:runId,object_id:objectId,payload:{result,canonical_path:rel,provenance_id:prov.provenance_id}});enqueueImpact(vault,{source_object:objectId,project_id:r.project.project_id,reason:'run completion requires project truth and learning review',affected_objects:[`obj-${r.project.project_id.slice(4)}`],actions:['review-current-state','review-execution-queue','compile-experience']});console.log(JSON.stringify({run_id:runId,object_id:objectId,project_id:r.project.project_id,result,canonical_path:rel,event_id:evt.event_id},null,2));
